version: '2'

volumes:
  postgresdb:
  redisdb:
  public:
  letsencrypt:

services:
  cartodb-postgis:
    #image: sabman/ihmeuw-cartodb-docker_cartodb-postgis
    container_name: cartodb-postgis
    build:
      context: postgis
    volumes:
      - postgresdb:/var/lib/postgresql/data
  cartodb-redis:
    #image: sabman/ihmeuw-cartodb-docker_cartodb-redis
    container_name: cartodb-redis
    build:
      context: redis
    volumes:
      - redisdb:/var/lib/redis
  cartodb-sqlapi:
    #image: sabman/ihmeuw-cartodb-docker_cartodb-sqlapi
    depends_on:
      - cartodb-postgis
      - cartodb-redis
    container_name: cartodb-sqlapi
    build:
      context: sqlapi
    command: $ENVIRONMENT.js.example
    environment:
      - ENVIRONMENT
  cartodb-mapsapi:
    #image: sabman/ihmeuw-cartodb-docker_cartodb-mapsapi
    depends_on:
      - cartodb-postgis
      - cartodb-redis
    container_name: cartodb-mapsapi
    build:
      context: mapsapi
    command: $ENVIRONMENT.js.example
    environment:
      - PUBLIC_HOST
      - PUBLIC_PORT
      - ENVIRONMENT
  cartodb-editor:
    image: sabman/ihmeuw-cartodb-docker_cartodb-editor
    depends_on:
      - cartodb-postgis
      - cartodb-redis
      - cartodb-mapsapi
      - cartodb-sqlapi
    container_name: cartodb-editor
    build:
      context: editor
      args:
        - RAILS_ENV=$ENVIRONMENT
    volumes:
      - public:/cartodb/public
      - ./migrated:/migrated
    environment:
      - PUBLIC_HOST
      - PUBLIC_PORT
      - PUBLIC_PROTOCOL
      - DEFAULT_USER
      - DEFAULT_PASSWORD
  cartodb-resque:
    image: sabman/ihmeuw-cartodb-docker_cartodb-editor
    depends_on:
      - cartodb-postgis
      - cartodb-redis
      - cartodb-mapsapi
      - cartodb-sqlapi
    container_name: cartodb-resque
    environment:
      - START_RESQUE_ONLY=1
      - PUBLIC_HOST
      - PUBLIC_PORT
      - PUBLIC_PROTOCOL
      - DEFAULT_USER
      - DEFAULT_PASSWORD
      - ENVIRONMENT
    volumes_from:
      - cartodb-editor
  cartodb-router:
    #image: sabman/ihmeuw-cartodb-docker_cartodb-router
    depends_on:
      - cartodb-mapsapi
      - cartodb-sqlapi
      - cartodb-editor
    container_name: cartodb-router
    build:
      context: router
    volumes:
      - public:/public:ro
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      - EMAIL
      - DOMAINS
